import {setTimeout as delay} from 'node:timers/promises';
import {chromium,expect} from '@playwright/test';import assert from 'node:assert/strict';import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {sample,multiline} from '../../src/examples.mjs';import {compile,parseProject,createProject} from '../../src/core.mjs';import {exportsFor} from '../../src/export.mjs';import {tableText} from '../../src/state.mjs';
const out='tests/browser/artifacts';await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,chromiumSandbox:true}),context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage(),done=[],errors=[],downloads=[];let acceptDialog=false;page.on('dialog',async d=>acceptDialog?d.accept():d.dismiss());page.on('pageerror',error=>errors.push(error.message));const base=process.env.BASE_URL||'http://127.0.0.1:4173';const step=async(name,fn)=>{await fn();done.push(name);console.log('PASS '+name);};
async function load(p){await page.locator('#format').selectOption('project');await page.locator('#source').fill(JSON.stringify(p));await page.locator('#read').click();await expect(page.locator('#title')).toHaveValue(p.title);await page.locator('#apply').click();await expect(page.locator('#dirty')).not.toBeVisible();await expect(page.locator('#record-count')).toHaveText(String(compile(p).records.length));}
// Respect Chromium's ten-download burst window without changing browser protections.
// https://github.com/chromium/chromium/blob/main/third_party/blink/renderer/core/frame/local_frame.cc
let lastDownloadStart=-Infinity;
async function download(key,name){
  const pause=Math.max(0,200-(performance.now()-lastDownloadStart));if(pause)await delay(pause);
  const started=performance.now();lastDownloadStart=started;
  const record={key,requestedName:name??null,startedMs:Math.round(started),status:'requested'};downloads.push(record);
  try{
    const [file]=await Promise.all([page.waitForEvent('download'),page.locator(`[data-export="${key}"]`).click()]);
    record.suggestedFilename=file.suggestedFilename();record.failure=await file.failure();assert.equal(record.failure,null,`Download failed: ${key}`);
    const path=`${out}/${name||file.suggestedFilename()}`;await file.saveAs(path);const content=await readFile(path,'utf8');record.bytes=Buffer.byteLength(content);record.status='saved';return content;
  }catch(error){record.status='failed';record.error=String(error);record.notice=await page.locator('#notice').textContent().catch(()=>null);throw new Error(`Download ${key} (${name??'default name'}) failed; notice=${record.notice}`,{cause:error});}
}
try{
await step('sample has exact grouped records, padding and unique DOM identities',async()=>{await page.goto(base);await expect(page.locator('#record-count')).toHaveText('3');await expect(page.locator('#source-count')).toHaveText('7');await expect(page.locator('#padding-count')).toHaveText('2');await expect(page.locator('#slots [data-row]')).toHaveCount(3);assert.deepEqual(await page.locator('#slots [data-row]').evaluateAll(els=>els.map(e=>e.dataset.row)),['1','3','4']);assert.equal(await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.length===new Set(ids).size;}),true);await page.screenshot({path:`${out}/desktop-en.png`,fullPage:true});});
await step('keyboard controls trace source values and Japanese language preserves state',async()=>{await page.locator('[data-row="3"]').focus();await page.keyboard.press('Enter');await expect(page.locator('#source-detail')).toContainText('Build a prototype');await page.locator('[data-lang="ja"]').click();await expect(page.locator('html')).toHaveAttribute('lang','ja');await expect(page.locator('#source-detail')).toContainText('Build a prototype');await page.screenshot({path:`${out}/desktop-ja.png`,fullPage:true});await page.locator('[data-lang="en"]').click();});
await step('capacity drafts lock every download and regenerate ceil counts',async()=>{await page.locator('#capacity').selectOption('2');await expect(page.locator('#dirty')).toBeVisible();await expect(page.locator('[data-export="merge"]')).toBeDisabled();await expect(page.locator('[data-export="project"]')).toBeDisabled();await expect(page.locator('#record-count')).toHaveText('3');await page.locator('#apply').click();await expect(page.locator('#record-count')).toHaveText('4');await expect(page.locator('#padding-count')).toHaveText('1');await page.locator('#group-column').selectOption('');await page.locator('#apply').click();await expect(page.locator('#order-note')).toContainText('unchanged');assert.deepEqual(await page.locator('#slots [data-row]').evaluateAll(els=>els.map(e=>e.dataset.row)),['1','2']);});
await step('group filters and record navigation retain real-versus-padding presence',async()=>{await load(sample);await page.locator('#group-filter').selectOption('g2');await expect(page.locator('#slots .padded')).toHaveCount(1);await expect(page.locator('#slots [data-row]')).toHaveCount(2);await page.locator('#group-filter').selectOption('');await page.locator('[data-nav="1"]').click();await expect(page.locator('#record-select')).toBeFocused();assert.deepEqual(await page.locator('#slots [data-row]').evaluateAll(els=>els.map(e=>e.dataset.row)),['6','7']);await expect(page.locator('#slots .padded')).toHaveCount(1);});
await step('eight deterministic downloads and project reimport preserve exact recipe',async()=>{await load(sample);for(const file of exportsFor(sample))assert.equal(await download(file.key),file.content,file.key);assert.deepEqual(parseProject(await readFile(`${out}/mergepanel-project.json`,'utf8')),sample);await page.locator('#format').selectOption('project');await page.locator('#file').setInputFiles({name:'project.json',mimeType:'application/json',buffer:Buffer.from(await readFile(`${out}/mergepanel-project.json`))});await expect(page.locator('#source')).toHaveValue(await readFile(`${out}/mergepanel-project.json`,'utf8'));await page.locator('#read').click();await page.locator('#apply').click();await expect(page.locator('#record-count')).toHaveText('3');});
await step('machine CSV retains image markers and formulas while review CSV explicitly alters them',async()=>{const p=structuredClone(sample);p.table.rows[0][2]='=SUM(1,2)';await load(p);const machine=await download('merge','formula-machine.csv'),review=await download('review','formula-review.csv');assert.ok(machine.includes('@slot_1_f005'));assert.ok(!machine.includes("'@slot_1_f005"));assert.ok(machine.includes('"=SUM(1,2)"'));assert.ok(review.includes("'@slot_1_f005"));assert.ok(review.includes('"\'=SUM(1,2)"'));assert.deepEqual(parseProject(await download('project','formula-project.json')),p);});
await step('conservative multiline block and explicit space policy retain source and receipts',async()=>{await load(multiline);await expect(page.locator('[data-export="merge"]')).toBeDisabled();await expect(page.locator('[data-export="proof"]')).toBeEnabled();await expect(page.locator('#blocked-count')).toHaveText('2');await page.locator('#multiline').selectOption('space');await page.locator('#apply').click();await expect(page.locator('#changed-count')).toHaveText('2');await expect(page.locator('[data-export="merge"]')).toBeEnabled();const receipt=JSON.parse(await download('changes','space-changes.json'));assert.equal(receipt.changes[0].original,'Line one\r\nLine two');assert.equal(receipt.changes[0].replacement,'Line one Line two');assert.equal(receipt.changes[1].breaks,2);await expect(page.locator('#slots')).toContainText('Line one Line two');const p=parseProject(await download('project','space-project.json'));assert.equal(p.table.rows[0][3],'Line one\r\nLine two');});
await step('image paths and identity values block replacement instead of being rewritten',async()=>{const p=structuredClone(multiline);p.settings.multiline='space';p.table.rows[0][4]='images/part\nname.jpg';await load(p);await expect(page.locator('[data-export="merge"]')).toBeDisabled();const receipt=JSON.parse(await download('changes','blocked-image-changes.json'));assert.ok(receipt.blocked.some(x=>x.kind==='image'&&x.value==='images/part\nname.jpg'));assert.ok(!receipt.changes.some(x=>x.column===4));await expect(page.locator('#slots .image-path .literal-text').first()).toHaveText('images/part\nname.jpg');});
await step('exact-header source update preserves tokens after column reorder and rejects missing bindings',async()=>{await load(sample);const order=[4,2,0,3,1],table={columns:order.map(i=>sample.table.columns[i]),rows:sample.table.rows.map(row=>order.map(i=>row[i]))};await page.locator('#format').selectOption('csv');await page.locator('#source-action').selectOption('update');await page.locator('#source').fill(tableText({...sample,table},'csv'));await page.locator('#read').click();await expect(page.locator('#group-column')).toHaveValue('4');await expect(page.locator('#id-column')).toHaveValue('2');await page.locator('#apply').click();const rebound=parseProject(await download('project','rebound-project.json'));assert.equal(rebound.settings.fields.find(f=>f.token==='f005').column,0);await page.locator('#source').fill('X,Y\na,b');await page.locator('#read').click();await expect(page.locator('#notice')).toContainText('missing column');await expect(page.locator('#record-count')).toHaveText('3');await expect(page.locator('#source')).toHaveValue('X,Y\na,b');await page.locator('#revert').click();});
await step('rejected CSV and invalid IDs preserve applied state; language and reset keep drafts explicit',async()=>{await page.locator('#source-action').selectOption('new');await page.locator('#source').fill('A,B\nwrong');await page.locator('#read').click();await expect(page.locator('#notice')).toContainText('entries');await page.locator('[data-lang="ja"]').click();await expect(page.locator('#source')).toHaveValue('A,B\nwrong');await page.locator('[data-lang="en"]').click();await page.locator('#revert').click();await page.locator('#id-column').selectOption('4');await page.locator('#apply').click();await expect(page.locator('#notice')).toContainText('unique');await expect(page.locator('#record-count')).toHaveText('3');await page.locator('#revert').click();});
await step('sample replacement cancellation and confirmation protect unsaved work',async()=>{await page.locator('#title').fill('Keep me');await page.locator('[data-example="multiline"]').click();await expect(page.locator('#title')).toHaveValue('Keep me');acceptDialog=true;await page.locator('[data-example="sample"]').click();await expect(page.locator('#title')).toHaveValue(sample.title);acceptDialog=false;await expect(page.locator('#dirty')).not.toBeVisible();});
await step('repeated file selection and malformed UTF-8 distinguish a real replacement character',async()=>{const before=await page.locator('#source').inputValue();await page.locator('#file').setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from([255])});await expect(page.locator('#notice')).toContainText('valid UTF-8');await expect(page.locator('#source')).toHaveValue(before);for(let i=0;i<2;i++){await page.locator('#file').setInputFiles({name:'same.csv',mimeType:'text/csv',buffer:Buffer.from('Heading\n\ufffd')});await expect(page.locator('#source')).toHaveValue('Heading\n\ufffd');}await page.locator('#read').click();await page.locator('#apply').click();await expect(page.locator('#source-count')).toHaveText('1');await expect(page.locator('#slots')).toContainText('\ufffd');});
await step('held asynchronous read cannot overwrite a newer example',async()=>{await page.evaluate(()=>{window.originalRead=File.prototype.arrayBuffer;File.prototype.arrayBuffer=function(){return new Promise(resolve=>{window.releaseRead=()=>window.originalRead.call(this).then(resolve);});};});await page.locator('#file').setInputFiles({name:'late.csv',mimeType:'text/csv',buffer:Buffer.from('Heading\nold')});await expect.poll(()=>page.evaluate(()=>typeof window.releaseRead)).toBe('function');acceptDialog=true;await page.locator('[data-example="sample"]').click();await expect(page.locator('#title')).toHaveValue(sample.title);acceptDialog=false;await page.evaluate(async()=>{File.prototype.arrayBuffer=window.originalRead;await window.releaseRead();});await expect(page.locator('#source')).not.toHaveValue('Heading\nold');await expect(page.locator('#source-count')).toHaveText('7');});
await step('maximum input exports every source exactly once across 250 eight-slot records',async()=>{const p={schema:'mergepanel.project.v1',title:'Maximum synthetic fixture',table:{columns:Array.from({length:10},(_,i)=>`Field ${i+1}`),rows:Array.from({length:2000},(_,i)=>Array.from({length:10},(_,j)=>`R${i+1}F${j+1}`))},settings:{capacity:8,group:null,id:0,fields:Array.from({length:10},(_,i)=>({token:`f${String(i+1).padStart(3,'0')}`,column:i,kind:i===9?'image':'text',enabled:true})),profile:'generic',multiline:'preserve'}};await load(p);await expect(page.locator('#record-count')).toHaveText('250');await expect(page.locator('#padding-count')).toHaveText('0');await page.locator('#record-select').selectOption('249');await expect(page.locator('#slots')).toContainText('R2000F10');const placement=JSON.parse(await download('placement-json','maximum-placement.json'));assert.equal(placement.placements.length,2000);assert.equal(new Set(placement.placements.map(x=>x.row)).size,2000);assert.equal(placement.records.length,250);assert.equal(parseProject(await download('project','maximum-project.json')).table.rows.length,2000);});
await step('wide ASCII/CJK and hostile text stay contained in desktop and mobile controls',async()=>{const p=structuredClone(sample);p.title='<script>window.injected=1</script>';p.table.rows[0][2]='W'.repeat(240);p.table.rows[0][3]='界'.repeat(240);p.table.rows[0][4]='https://example.invalid/<img onerror=bad>';await load(p);assert.equal(await page.evaluate(()=>window.injected),undefined);await expect(page.locator('#slots img,#slots script')).toHaveCount(0);await page.screenshot({path:`${out}/wide-labels.png`,fullPage:true});await load(sample);for(const width of [768,390,320]){await page.setViewportSize({width,height:900});for(const language of ['ja','en']){await page.locator(`[data-lang="${language}"]`).click();await expect(page.locator('html')).toHaveAttribute('lang',language);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow ${language}/${width}`);for(const button of ['ja','en']){const m=await page.locator(`[data-lang="${button}"]`).evaluate(el=>{const r=document.createRange();r.selectNodeContents(el);return{lines:new Set([...r.getClientRects()].map(x=>Math.round(x.top))).size,right:el.getBoundingClientRect().right,viewport:innerWidth};});assert.equal(m.lines,1,JSON.stringify(m));assert.ok(m.right<=m.viewport);}await page.screenshot({path:`${out}/mobile-${language}-${width}.png`,fullPage:true});}}await page.locator('#capacity').selectOption('1');await page.locator('#apply').click();await expect(page.locator('#record-count')).toHaveText('7');});
await step('standalone field and proof HTML contain every layout and print cleanly without assets',async()=>{await load(sample);for(const key of ['fields','proof']){const html=await download(key),report=await context.newPage(),requests=[];report.on('request',request=>requests.push(request.url()));await report.setContent(html);await expect(report.locator('h1')).toHaveText(sample.title);await expect(report.locator('img,script')).toHaveCount(0);if(key==='proof'){await expect(report.locator('.record')).toHaveCount(3);await expect(report.locator('.slot')).toHaveCount(9);}await report.emulateMedia({media:'print'});await report.pdf({path:`${out}/${key}.pdf`,format:'A4',printBackground:true});await report.screenshot({path:`${out}/${key}-print.png`,fullPage:true});assert.deepEqual(requests,[]);await report.close();}await page.emulateMedia({media:'print'});await expect(page.locator('.print-note')).toBeVisible();await page.emulateMedia({media:'screen'});});
await step('source update retains an unapplied recipe and invalid draft corrections remain accessible',async()=>{
  await page.setViewportSize({width:1440,height:1000});await load(sample);await page.locator('#title').fill('Pending recipe');await page.locator('#capacity').selectOption('1');
  await page.locator('#format').selectOption('csv');await page.locator('#source-action').selectOption('update');await page.locator('#source').fill(tableText(sample,'csv'));await page.locator('#read').click();
  await expect(page.locator('#title')).toHaveValue('Pending recipe');await expect(page.locator('#capacity')).toHaveValue('1');await expect(page.locator('#record-count')).toHaveText('3');
  await page.locator('#title').fill('');const changed=structuredClone(sample);changed.table.rows[0][2]='Updated literal';await page.locator('#source').fill(tableText(changed,'csv'));await page.locator('#read').click();
  await expect(page.locator('#notice')).toContainText('Title');await expect(page.locator('#title')).toBeEnabled();await page.locator('#title').fill('Corrected recipe');await page.locator('#read').click();await page.locator('#apply').click();
  await expect(page.locator('#record-count')).toHaveText('7');const p=parseProject(await download('project','retained-draft-project.json'));assert.equal(p.title,'Corrected recipe');assert.equal(p.settings.capacity,1);assert.equal(p.table.rows[0][2],'Updated literal');
});
await step('literal marker-like data is distinct from empty, unset and padding states',async()=>{
  const p=createProject({columns:['Value','Group','ID'],rows:[['','', '(ordinal only)'],['(empty string)','(blank exact group)','Ordinal identity'],['Empty string','(grouping disabled)','3'],['“x”','Grouping disabled','4']]});p.settings.group=1;await load(p);
  await expect(page.locator('#slots .slot-card').first().locator('.slot-field .value-marker').first()).toHaveText('Empty string');await expect(page.locator('.record-heading .value-marker')).toHaveText('Blank exact group');await expect(page.locator('#slots .item-id .value-marker').first()).toHaveText('Ordinal identity');
  await page.locator('[data-row="1"]').click();await expect(page.locator('#source-detail .value-marker').first()).toHaveText('Empty string');await expect(page.locator('#slots .padded')).toHaveCount(2);
  await page.locator('#group-filter').selectOption('g2');await expect(page.locator('.record-heading .literal-text')).toHaveText('(blank exact group)');await expect(page.locator('#slots .slot-field .literal-text').first()).toHaveText('(empty string)');
  await page.locator('#id-column').selectOption('2');await page.locator('#apply').click();await expect(page.locator('#slots .item-id .literal-text').first()).toHaveText('(ordinal only)');
  const report=await context.newPage();await report.setContent(await download('proof','marker-proof.html'));await expect(report.locator('.value-marker')).not.toHaveCount(0);await expect(report.locator('.literal-text').filter({hasText:'(empty string)'})).toHaveCount(1);await report.close();
});
await step('failed newer read and generation attempts cancel pending file reads',async()=>{
  for(const action of ['read','apply']){
    await load(sample);if(action==='read'){await page.locator('#format').selectOption('csv');await page.locator('#source').fill('A,B\nragged');}else await page.locator('#title').fill('');
    const source=await page.locator('#source').inputValue();await page.evaluate(()=>{window.originalRead=File.prototype.arrayBuffer;File.prototype.arrayBuffer=function(){return new Promise(resolve=>{window.releaseRead=()=>window.originalRead.call(this).then(resolve);});};});
    await page.locator('#file').setInputFiles({name:'superseded.csv',mimeType:'text/csv',buffer:Buffer.from('New\nlate')});await expect.poll(()=>page.evaluate(()=>typeof window.releaseRead)).toBe('function');await page.locator(`#${action}`).click();await expect(page.locator('#notice')).toContainText(action==='read'?'entries':'Title');
    await page.evaluate(async()=>{File.prototype.arrayBuffer=window.originalRead;await window.releaseRead();delete window.releaseRead;});await expect(page.locator('#source')).toHaveValue(source);await expect(page.locator('#record-count')).toHaveText('3');await expect(page.locator('#dirty')).toBeVisible();
  }
});
await step('oversized complete proof is refused while exact machine and project exports remain usable',async()=>{
  const p=createProject({columns:Array.from({length:12},(_,i)=>`${i}${'&'.repeat(238)}`),rows:Array.from({length:2000},(_,i)=>[String(i),...Array(11).fill('&'.repeat(240))])});p.settings.capacity=8;p.settings.group=0;await load(p);await expect(page.locator('#record-count')).toHaveText('2000');
  const proofDownloads=[];const track=download=>proofDownloads.push(download);page.on('download',track);await page.locator('[data-export="proof"]').click();await expect(page.locator('#notice')).toContainText('exceeds 8 MiB');await expect(page.locator('#notice')).toContainText('No partial proof');assert.equal(proofDownloads.length,0);page.off('download',track);
  assert.deepEqual(parseProject(await download('project','large-proof-project.json')),p);const machine=await download('merge','large-proof-machine.csv');assert.equal(machine.split('\r\n').length,2002);assert.ok(machine.includes('&'.repeat(240)));await expect(page.locator('[data-export="merge"]')).toBeEnabled();await load(sample);
});
await step('application performs no external requests and has no uncaught errors',async()=>{const requests=[],fresh=await context.newPage();fresh.on('request',request=>requests.push(request.url()));await fresh.goto(base);await expect(fresh.locator('#source-count')).toHaveText('7');assert.ok(requests.every(url=>url.startsWith(base+'/')));await fresh.close();assert.deepEqual(errors,[]);});
await writeFile(`${out}/results.json`,JSON.stringify({status:'passed',chromiumSandbox:true,checks:done,downloads,browserVersion:browser.version(),uncaughtErrors:errors},null,2));
}catch(error){await page.screenshot({path:`${out}/failure.png`,fullPage:true}).catch(()=>{});await writeFile(`${out}/results.json`,JSON.stringify({status:'failed',chromiumSandbox:true,checks:done,downloads,browserVersion:browser.version(),error:String(error),uncaughtErrors:errors},null,2));throw error;}finally{await context.close();await browser.close();}
