import test from 'node:test';import assert from 'node:assert/strict';import {createDOM} from './dom-stub.mjs';import {sample,multiline} from '../src/examples.mjs';import {tableText} from '../src/state.mjs';
let serial=0;async function app(){const dom=createDOM();globalThis.document=dom.document;globalThis.window=dom.window;dom.window.confirm=()=>true;await import(`../src/app.mjs?test=${serial++}`);const get=id=>dom.document.getElementById(id);return{...dom,get,change:async(id,value,type='change')=>{const el=get(id);el.value=value;await el.emit(type);},click:async selector=>{const el=dom.document.querySelector(selector);assert.ok(el,selector);await el.emit('click');await get('app').emit('click',{target:el});}};}
test('initial actual handlers show grouped order and source/padding counts',async()=>{const a=await app();assert.equal(a.get('record-count').textContent,'3');assert.equal(a.get('source-count').textContent,'7');assert.equal(a.get('padding-count').textContent,'2');assert.equal(a.get('slots').querySelectorAll('[data-row]').length,3);assert.match(a.get('order-note').textContent,/changed/);const ids=a.document.querySelectorAll('[id]').map(e=>e.id);assert.equal(ids.length,new Set(ids).size);});
test('capacity drafts lock exports until applied and reset navigation',async()=>{const a=await app();await a.change('capacity','2');assert.equal(a.get('dirty').hidden,false);assert.equal(a.document.querySelector('[data-export="merge"]').disabled,true);assert.equal(a.get('record-count').textContent,'3');await a.click('#apply');assert.equal(a.get('record-count').textContent,'4');assert.equal(a.get('padding-count').textContent,'1');assert.equal(a.document.querySelector('[data-export="merge"]').disabled,false);});
test('group filtering and record navigation show exact real/padded slots',async()=>{const a=await app();await a.change('group-filter','g2');assert.equal(a.get('slots').querySelectorAll('[data-row]').length,2);assert.equal(a.get('slots').querySelectorAll('.padded').length,1);await a.click('[data-row="2"]');assert.match(a.get('source-detail').textContent,/Show your work/);await a.change('group-filter','');await a.click('[data-nav="1"]');assert.equal(a.get('slots').querySelectorAll('[data-row]').length,2);assert.equal(a.document.activeElement.id,'record-select');});
test('actual profile and multiline handlers block then replace without changing the source',async()=>{const a=await app();await a.click('[data-example="multiline"]');assert.equal(a.get('blocked-count').textContent,'2');assert.equal(a.document.querySelector('[data-export="merge"]').disabled,true);assert.equal(a.document.querySelector('[data-export="project"]').disabled,false);await a.change('multiline','space');await a.click('#apply');assert.equal(a.get('changed-count').textContent,'2');assert.equal(a.document.querySelector('[data-export="merge"]').disabled,false);assert.ok(a.get('source').value.includes('Line one\r\nLine two'));assert.ok(a.get('slots').textContent.includes('Line one Line two'));});
test('field toggles and image declaration are staged; selecting no fields rejects atomically',async()=>{const a=await app();for(const el of a.document.querySelectorAll('[data-enabled]')){el.checked=false;await el.emit('change');}await a.click('#apply');assert.match(a.get('notice').textContent,/Select 1/);assert.equal(a.get('source-count').textContent,'7');await a.click('#revert');assert.equal(a.get('dirty').hidden,true);assert.equal(a.document.querySelectorAll('[data-enabled]').filter(x=>x.checked).length,3);});
test('language changes preserve malformed source and draft settings',async()=>{const a=await app();await a.change('source','A,B\ninvalid','input');await a.click('#read');await a.click('[data-lang="ja"]');assert.equal(a.get('source').value,'A,B\ninvalid');assert.equal(a.get('apply').disabled,true);await a.click('#revert');assert.equal(a.get('source-count').textContent,'7');});
test('exact-header update rebinds roles despite source-column order changes',async()=>{const a=await app(),order=[4,0,3,1,2],table={columns:order.map(i=>sample.table.columns[i]),rows:sample.table.rows.map(r=>order.map(i=>r[i]))};await a.change('source-action','update');await a.change('source',tableText({...sample,table},'csv'),'input');await a.click('#read');assert.equal(a.get('group-column').value,'3');assert.equal(a.get('id-column').value,'1');await a.click('#apply');assert.equal(a.get('record-count').textContent,'3');assert.match(a.get('slots').textContent,/Paper circuits/);});
test('file import uses fatal decoding and repeat selection preserves genuine U+FFFD',async()=>{const a=await app(),before=a.get('source').value;let input=a.get('file');input.files=[new Blob([new Uint8Array([255])])];await input.emit('change');assert.match(a.get('notice').textContent,/UTF-8/);assert.equal(a.get('source').value,before);for(let i=0;i<2;i++){input=a.get('file');input.files=[new Blob(['A\n\ufffd'])];await input.emit('change');assert.equal(a.get('source').value,'A\n\ufffd');}await a.click('#read');await a.click('#apply');assert.equal(a.get('source-count').textContent,'1');});
test('pending file cannot replace newer sample and cancelled replacement retains drafts',async()=>{const a=await app();let resolve;const pending=new Promise(r=>resolve=r),file=a.get('file');file.files=[{size:4,arrayBuffer:()=>pending}];const reading=file.emit('change');await a.click('[data-example="multiline"]');resolve(new TextEncoder().encode('old').buffer);await reading;assert.equal(a.get('title').value,multiline.title);await a.change('title','Keep','input');a.window.confirm=()=>false;await a.click('[data-example="sample"]');assert.equal(a.get('title').value,'Keep');assert.equal((await a.window.emit('beforeunload')).defaultPrevented,true);});
